name: parser CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

permissions:
  contents: read
  
env:
  CONFIG_FILE_PATH: ./conf/conf.env
  BASE_URL: https://api.aiven.io

jobs:
  test_parser:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        [[ -f requirements.txt ]] && pip install -r requirements.txt

    - name: Set temporary config file
      run: |
        cat <<EOF > $CONFIG_FILE_PATH
        #!/bin/bash
        PROJECT=${{ vars.PROJECT }}
        TOKEN=${{ secrets.TOKEN }}
        BASE_URL=$BASE_URL
        EOF

    - name: Run main.py script
      run: |
        python main.py

    - name: Check that the script created the files
      run: |
        file_name="graph_data.dot"
        [[ -f ./$file_name ]] && echo "$file_name created - OK" || exit 1
        file_name="graph_data.gml"
        [[ -f ./$file_name ]] && echo "$file_name created - OK" || exit 1
        file_name="nx.html"
        [[ -f ./$file_name ]] && echo "$file_name created - OK" || exit 1

    - name: Run app.py server
      run: |
        python app.py &
    - name: Check that the server is reachable
      run: |
        head=$(curl --head http://127.0.0.1:8050/ | head -n 1)
        [[ $head = *"200 OK"* ]] && echo "$head" || exit 1

  do_something_else:
    runs-on: ubuntu-latest
    needs: test_parser
    steps:
    - run: echo "Doing something else"
