name: parser CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test_parser:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - name: python_setup
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: install_dependencies
      run: |
        echo "python -m pip install --upgrade pip"
        echo "pip install -r requirements.txt"
